import { makeStyles } from '@material-ui/core';
export default makeStyles((theme) => ({
  container: {
    height: 2079,
    backgroundSize: 'cover',
    background: 'none',
    maxWidth: '100%',
    paddingLeft: 0,
    paddingRight: 0,
  },
  media: {
    height: 0,
    paddingTop: '65%',
  },
  border: {
    border: 'solid',
  },
  fullHeightCard: {
    height: '100%',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    background: '#111229',
    borderRadius: '8px',
    height: '100%',
    position: 'relative',
    zIndex: 1,
  },
  grid: {
    display: 'flex',
  },
  details: {
    display: 'flex',
    justifyContent: 'space-between',
    margin: '20px',
  },
  title: {
    padding: '0 20px',
    fontFamily: "Libre Baskerville",
    fontSize: "20px",
    fontStyle: "normal",
    fontWeight: 700,
    lineHeight: "32px",
    letterSpacing: "0em",
    textAlign: "left",
    color: '#FFFFFF',
  },
  content: {
    fontFamily: 'Nunito',
    fontSize: '15px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '14px',
    letterSpacing: '0em',
    textAlign: 'left',
    color: '#682F26',
    background: '#E5C558',
    paddingLeft: '3px',
    paddingRight: '3px',
  },
  info: {
    fontFamily: "Nunito",
    fontSize: "16px", fontStyle: "normal",
    fontWeight: 600, lineHeight: "32px",
    letterSpacing: "0em", textAlign: "left",
    color: '#0259EB',
    paddingLeft: '4px',
    cursor: 'pointer'
  },
  user: {
    background: '#0A0B1A',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    borderRadius: '16px',
    height: '300px',
    position: 'relative',
    border: '2px solid #E5AF56',
    boxSizing: 'border-box',
    zIndex: 1,
  },
  newUser: {
    fontFamily: "Quattrocento",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 700, lineHeight: "32px",
    letterSpacing: "0em",
    textAlign: "left",
    color: "#FFFFFF",
  },
  location: {
    fontFamily: "Nunito",
    fontSize: "15px", fontStyle: "normal",
    fontWeight: "600",
    lineHeight: "16px",
    letterSpacing: "0em",
    textAlign: "left",
    color: "#E5C558",
    paddingLeft: '10px',
    paddingTop: '4px'
  },
  cardContent: {
    position: "absolute",
    top: "110px",
    left: "25px",
  },
  typoReview: {
    fontFamily: "Nunito",
    fontSize: "17px", fontStyle: "normal",
    fontWeight: "400",
    lineHeight: "24px",
    letterSpacing: "0em",
    textAlign: "left",
    color: "#FFFFFF",
  },
  cari: {
    fontFamily: 'Libre Baskerville',
    fontSize: '80px',
    fontStyle: 'normal',
    fontWeight: 700,
    lineHeight: '96px',
    letterSpacing: '0em',
    textAlign: 'left',
    color: '#FFFFFF',
    [theme.breakpoints.between('xs', 'sm')]: {
      fontSize: '60px',
    },
    [theme.breakpoints.down('xs')]: {
      fontSize: '48px',
    },
    // [theme.breakpoints.up('lg')]: {
    //   backgroundColor: green[500],
    // },
  },
  text: {
    fontFamily: 'Nunito',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '32px',
    letterSpacing: '0em',
    textAlign: 'left',
    color: '#FFFFFF',
    [theme.breakpoints.between('xs', 'sm')]: {
      fontSize: '20px',
    },
    [theme.breakpoints.down('xs')]: {
      fontSize: '16px',
    },
  }
}))